#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                ğŸ’»Galaxy Graves ConfigğŸ’»
#                                                  ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                ğŸ’»Galaxy Graves ConfigğŸ’»
#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 1.0'
ConfigVersion: '1.0'

#âœâœâœâœâœPermissionsâœâœâœâœâœ

#âœâœâœâœâœPermissionsâœâœâœâœâœ

#####You can Modify the following how you wish#####



#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/ePQGvQuzG3
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default config file.
