#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥
#                                                ğŸ’»Galaxy Graves ConfigğŸ’»
#                                                  ğŸ”¥Coded By Mike3132ğŸ”¥
#                                                ğŸ’»Galaxy Graves ConfigğŸ’»
#                                                 ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥ğŸ–¥

Version: 'Version 1.0'
ConfigVersion: '1.0'

#âœâœâœâœâœPermissionsâœâœâœâœâœ
#GalaxyGraves.Command.Grave > Grants access to use the /grave command to see the location of all of their active graves
#GalaxyGraves.Command.Admin > Base admin permission (This is required for all admin commands)
#GalaxyGraves.Command.Admin.Reload > Grants access to reloading the plugins configuration files
#GalaxyGraves.Admin.ListActive > Graves access to listing all active graves for other players
#GalaxyGraves.Grave.Bypass > Grants access to claim graves that do not belong to them
#GalaxyGraves.Admin.Recover > Grants access to recover player inventories from the graves backup files

#ğŸ“ğŸ“ğŸ“ğŸ“
#WARNING: The following permissions grant access to extremely dangerous commands that can and will cause issues with graves if not used properly.
#WARNING: I am not responsible for you giving this out to random players and them causing corruptions with graves.

#GalaxyGraves.Admin.ForceRemove > Grants access to force removing active graves for other players.
#ğŸ“ğŸ“ğŸ“ğŸ“
#âœâœâœâœâœPermissionsâœâœâœâœâœ

#####You can Modify the following how you wish#####
#Should the plugin create a custom model for the grave using a model engine model.
#This requires model engine to be installed and for the model to be setup.
Model-Engine-Grave: false

#If you are choosing to use model engine please supply the models name here
Model-Engine-Grave-Name: "devstone"

#If you want the plugin to send a message when a player dies.
#You can configure how this message looks in the messages.yml
Player-Death-Message: true

#If you want the plugin to send a message to the player when their items are returned from the grave
#You can configure how this message looks in the messages.yml
Grave-Return-Item-Message: true

#The distance from a grave in which pistons are disabled. (This is a square root, so think of it as a big cube)
#WARNING: IF YOU SET THIS TO LESS THAN 3 AND A PLAYER USES A PISTON TO MOVE A GRAVE THE PLUGIN MAY NO LONGER REGISTER THE GRAVE.
#If this happens the only way to remove the grave is for an admin to force delete the grave from memory using /graves admin <playername> ForceRemove
Grave-Distance-To-Piston: 10

#How long should a grave last before it's automatically removed from the world?
#This is in minutes so 5 = 5 minutes.
Grave-Lifetime: 5

#If you want the plugin to send a message to the player when their grave expires.
#You can configure how this messages looks in the messages.yml
Player-Grave-Expire-Message: true

#Should players be allowed to take a grave that doesn't belong to them?
#Players with the "GalaxyGraves.Admin.Bypass" permission override this by default
#You can configure how this messages looks in the messages.yml
Player-Take-Others-Grave: false

#Should the plugin play an animation when a player claims their grave?
Claim-Animation: true

#Should the plugin play a sound when a player claims their grave?
Claim-Sound: true




#See messages.yml for all configurable plugin messages
#â™ If you have any questions please join my discord, open a support ticket and @Mike3132
#â™ https://discord.gg/ePQGvQuzG3
#â™ Thanks for downloading and have a wonderful day

#â™›â™›â™›â™›â™› END OF CONFIG â™›â™›â™›â™›â™›
#This is the default config file.
